from typing import Any

class UnicodeMixin:
    def __str__(self) -> str: ...

class ComparableMixin:
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
