from typing import Optional, Any

def output(
    text: str, decoder: Optional[str] = None, newline: bool = True, toStdout: bool = False, **kwargs: Any
) -> None: ...
def exception(
    msg: Optional[BaseException] = None,
    decoder: Optional[str] = None,
    newline: bool = True,
    tb: bool = False,
    **kwargs: Any,
) -> None: ...
def error(text: str, decoder: Optional[str] = None, newline: bool = True, **kwargs: Any) -> None: ...
def warning(text: str, decoder: Optional[str] = None, newline: bool = True, **kwargs: Any) -> None: ...
def log(text: str, decoder: Optional[str] = None, newline: bool = True, **kwargs: Any) -> None: ...
